version: 2
jobs:
  build:
    working_directory: ~/libra
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: libra-{{ checksum "libra/project.clj" }}
      - run: cd libra && lein with-profile +dev:+1.8:+1.9 deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: libra-{{ checksum "libra/project.clj" }}
      - run: cd libra && lein with-profile +dev:+1.8:+1.9 test
